# .github/workflows/build-and-release.yml
name: Build and Release

on:
  push:
    branches:
      - main  # or whichever branch you want

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make executable
        run: |
          chmod +x ./make
          ./make

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: ./out/make/AppImage/Qiqi's_Notebook-x86_64.AppImage
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
