# .github/workflows/build-and-release.yml

name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FUSE
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libfuse2

      - name: Set up Node.js 20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: |
          npm install
          npm install typescript@5.3.3

      - name: Make AppImage
        run: |
          chmod +x ./make
          chmod +x ./AppImageTool.AppImage
          ./make

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: "./out/make/AppImage/Qiqi's_Notebook-x86_64.AppImage"
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
