# .github/workflows/build-and-release.yml

name: Build and Release

on:
  push:
    branches:
      - master  # or the branch you want to use

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to create releases and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: |
          npm install
          npm install typescript@5.3.3

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage ~/appimagetool-x86_64.AppImage

      - name: Run make and capture all logs
        run: |
          echo "Running npm run make..."
          npm run make  # Run the make script
          echo "Finished running npm run make."
          # List the output directory to check if AppImage exists
          echo "Listing contents of out/make directory..."
          ls -R ./out/make/

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: ./out/make/AppImage/Qiqi\'s_Notebook-x86_64.AppImage  # Ensure this path is correct
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
