name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: |
          npm install
          npm install typescript@5.3.3

      - name: Make AppImage
        run: |
          chmod +x ./make
          chmod +x ./AppImageTool.AppImage
          ./make

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: List contents of out/make directory (for debugging)
        run: |
          ls -R ./out/make/

      - name: Upload Windows Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: "./out/make/squirrel.windows/Qiqi*.exe"  # Adjusted path pattern
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: "./out/make/dmg/*.dmg"  # Adjust path if needed
          make_latest: true
          file_name: "Qiqi's-Notebook-${{ env.VERSION }}.dmg"  # Added custom name for macOS release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Release (AppImage)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: "./out/make/AppImage/Qiqi\'s_Notebook-x86_64.AppImage"
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
